apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Build
        uses: docker://eclipse-temurin:21-alpine
        shell: sh
        run: |
          ./gradlew clean build;
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build container image with Kaniko
        # uses: cloudbees-io/kaniko@2207c0db170fcd1d0687a2e47b18f19714796c62
        # uses: cloudbees-io/kaniko@v1
        uses: cloudbees-io/kaniko
        with:
          send-artifact-flag: true
          destination:  docker.io/jyoungcb/docker-demo:0.0.1-${{cloudbees.version}}
