apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'


permissions:
  id-token: write

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
             
      - name: Build container image with Kaniko
        uses: cloudbees-io/kaniko@main
        with:
          context: .
          dockerfile: Dockerfile
          destination: docker.io/jyoungcb/docker-demo:0.0.1-${{cloudbees.version}}
          send-artifact-info: true
        env:
          registry: https://index.docker.io/v1/
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}